name: Build and Push Multi-Arch Docker Images to ECR

on:
  push:
    branches:
      - main
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        runs: echo "Checking out code"