name: Terraform Plan, Approval, and Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment:
      name: production   # This triggers the approval step
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      ARGOCD_HTTPS_SYNC: ${{ secrets.ARGOCD_HTTPS_SYNC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file="stage-env.tfvars"

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="stage-env.tfvars"

      - name: Run ArgoCD Setup Script
        run: |
          chmod +x ./cluster_conf/argo-prom-grafana.sh
          ./cluster_conf/argo-prom-grafana.sh
